// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace SpecFlow.WatiN.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Google search")]
    public partial class GoogleSearchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GoogleSearch.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Google search", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find SpecFlow technical concepts")]
        public virtual void FindSpecFlowTechnicalConcepts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find SpecFlow technical concepts", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("I go to http://www.google.com/en");
#line 5
testRunner.And("I fill in \"q\" with \"specflow\"");
#line 6
testRunner.When("I press \"Google Search\"");
#line 7
testRunner.Then("I should see \"SpecFlow - Pragmatic BDD for .NET\"");
#line 8
testRunner.When("I click \"SpecFlow - Pragmatic BDD for .NET\"");
#line 9
testRunner.And("I click \"specflow\"");
#line 10
testRunner.And("I click \"technical concepts\"");
#line 11
testRunner.Then("I should see \"We strive to be fully compatible with the Gherkin language\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find TekPub\'s \'Concepts\' image for SpecFlow video")]
        public virtual void FindTekPubSConceptsImageForSpecFlowVideo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find TekPub\'s \'Concepts\' image for SpecFlow video", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
testRunner.Given("I go to http://www.google.com/advanced_image_search?hl=en&sout=1");
#line 15
testRunner.And("I choose \"Use strict filtering\"");
#line 16
testRunner.And("I fill in \"as_q\" with \"specflow tekpub\"");
#line 17
testRunner.When("I press \"Google Search\"");
#line 18
testRunner.Then("I should see \"Tekpub - Concepts\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
